services:
    ioni_payzen.twig.twig_extension:
        class: Ioni\PayzenBundle\Twig\TwigExtension
        public: false
        tags:
          - { name: twig.extension }

    ioni_payzen.form_fields_generator:
        class: Ioni\PayzenBundle\Service\FormFieldsGenerator
        arguments: []
